name: Multiple Jobs
on: push
env:
  username: Rashi
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Rashi
      - run: echo 'Hi ${{ env.username }}'  # Hi Riya
        env:
          username: Octocat
  linux_job:
    runs-on: ubuntu-latest
    env:
      username: Tux
    steps:
      - run: echo 'Hi ${{ env.username }}'  # Hi Tux
